webtalk_init -webtalk_dir /home/joseph/school/year4/cpe439/logic_analyzer/logic_analyzer.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-11-28 11:07:13" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211124973_0_0_449" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "316lcoie5qq606o395jqkq1h6o" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3031.789 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1511889328000" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.2" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1511889328000"
webtalk_add_data -client sdk -key uid -value "1511889400000" -context "sdk\\\\bsp/1511889400000"
webtalk_add_data -client sdk -key hwid -value "1511889328000" -context "sdk\\\\bsp/1511889400000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1511889400000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1511889400000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1511889400000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1511896033950"
webtalk_transmit -clientid 3318895303 -regid "211124973_0_0_449" -xml /home/joseph/school/year4/cpe439/logic_analyzer/logic_analyzer.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/joseph/school/year4/cpe439/logic_analyzer/logic_analyzer.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/joseph/school/year4/cpe439/logic_analyzer/logic_analyzer.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
